# SEM SRP


class Order:
    # negócio
    def calculate_total_sum(self): ...
    def add_item(self): ...
    def remove_item(self): ...

    # apresentação
    def show_order(self): ...
    def print_order(self): ...

    # persistência
    def update(self): ...
    def save(self): ...
    def delete(self): ...
    def load(self): ...


# COM SRP


class Order:
    # negócio
    def calculate_total_sum(self): ...
    def add_item(self): ...
    def remove_item(self): ...


class OrderViewer:
    # apresentação
    def show_order(self): ...
    def print_order(self): ...


class OrderRepository:
    # persistência
    def update(self): ...
    def save(self): ...
    def delete(self): ...
    def load(self): ...
